# Generated by Django 5.2.4 on 2025-08-05 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_cuisine_type_restaurant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]