# Generated by Django 5.2.4 on 2025-08-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]