<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-08-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
=======
# Generated by Django 5.2.4 on 2025-08-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
>>>>>>> 39a144b3f68ac0f01775da573343fc5bd5d79b38
